version: '2.4'

services:

  redis:
    image: redis:4.0.10
    cpus: '0.25'
    mem_limit: '128m'
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:10.6
    cpus: '1'
    mem_limit: '1g'
    volumes:
      - postgres:/var/lib/simplesettler/postgresql/data
    ports:
      - "5432:5432"

volumes:
  redis:
    driver: local
  postgres:
    driver: local
