---
development:
  cloud_name: Rails.application.secrets.CLOUDINARY_CLOUD_NAME
  api_key: Rails.application.secrets.CLOUDINARY_CLOUD_KEY
  api_secret: Rails.application.secrets.CLOUDINARY_CLOUD_SECRET
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: Rails.application.secrets.CLOUDINARY_CLOUD_NAME
  api_key: Rails.application.secrets.CLOUDINARY_CLOUD_KEY
  api_secret: Rails.application.secrets.CLOUDINARY_CLOUD_SECRET
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: Rails.application.secrets.CLOUDINARY_CLOUD_NAME
  api_key: Rails.application.secrets.CLOUDINARY_CLOUD_KEY
  api_secret: Rails.application.secrets.CLOUDINARY_CLOUD_SECRET
  enhance_image_tag: true
  static_image_support: false
