---
development:
  cloud_name: Rails.application.secrets.cloudinary_cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: Rails.application.secrets.cloudinary_cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: Rails.application.secrets.cloudinary_cloud_name
  api_key: Rails.application.secrets.cloudinary_api_key
  api_secret: Rails.application.secrets.cloudinary_api_secret
  enhance_image_tag: true
  static_image_support: false

  # development:
  #   cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  #   api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  #   api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  #   enhance_image_tag: true
  #   static_image_support: false
  # production:
  #   cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  #   api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  #   api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  #   enhance_image_tag: true
  #   static_image_support: true
  # test:
  #   cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  #   api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  #   api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  #   enhance_image_tag: true
  #   static_image_support: false
